name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
        - uses: actions/checkout@v4
        - name: Installing Node.js #{{ matrix.node-version }}
          uses: actions/checkout@v4
          with:
            node-version: ${{ matrix.node-version }}
        - name: install modules
          run: npm install
        - name: build project
          run: npm run build
        - name: start unit test
          run: npm run test:unit
